### ISSUE TITLE
[IDEA] UnitOfWork

### ISSUE THREAD

**Issue by bakura10** [JouwWeb/SlmQueue#162]
Hi everyone,

When reading a bit about the command/event bus pattern, I often see things about asynchronous events.  When an event is triggered somewhere, multiple listeners may be hooked to the event bus. Some of those events would be done synchronously, but some of then would be done asynchronously.

However, one problem is that if you have, let's say, 3 events to do asynchronously, this would result in three requests (to SQS API for instance), hence reducing the advantage of using asynchronicity.

The idea is to create a kind of "commiter" (not sure of the same) in the SlmQueue project:

``` php
interface CommiterInterface
{
    public function addJob($queueName, JobInterface $job);
    public function commit();
}
```

An abstract class would be provided in SlmQueue for addJob, then each adapter would have its own commiter to implement commit. For instance on SQS, it could take advantage of the "batchPush", while providers not having batch methods could simply iterate through all jobs and push them all.

Then, in the code, instead of directly pushing to the queue, you would add it to the committer:

``` php
class Listener1
{
    public function doSomething()
    {
        $job = new DoSomething();
        $this->commiter->addJob('my_queue', $job); // Nothing is really added to the queue at this point
    }
}
```

``` php
class Listener2
{
    public function doSomethingElse()
    {
        $job = new DoSomethingElse();
        $this->commiter->addJob('my_queue', $job); // Nothing is really added at this point
    }
}
```

You could then have some kind of "post" event bus that would do the commit:

``` php
$this->commiter->commit(); // Push all the jobs to the queue(s) the most efficient way
```

What do you think of the idea?

ping @juriansluiman @basz

**Comment by ltouro** [comment]
What about something like this:

``` 
// This is still a queue for all matters
class EfficientQueue implements QueueInterface{
private $queue;
private $inMemoryJobs;

public function __construct($queue);

// add to in-memory jobs
public function push($job, $options);

// commit in memory jobs to the queue
public function __deconstruct()

// explicitily proxies the remaining interface methods to it the decorated queue
}
```
Just an ideia. I don't know how safe it is to use deconstruct.

**Comment by bakura10** [comment]
Yeah but the fact that it decorates a queue make it less flexible. My interface idea you could even push to different queue (potentially using different adapters) in a homogeneous way.

**Comment by basz** [comment]
Hi Bakura, I kind of follow what you are trying to solve here, please correct me if i'm wrong. 

"You don't want jobs added to the queue until all listeners are done mainly because it is inefficient to add them one by one to the queue"

I think this Commiter class would help you there, yes. No really appropriate to Doctrine though (see the 'update' at http://www.doctrine-project.org/2009/08/07/doctrine2-batch-processing.html )

The __destruct method is *not* a good idea. At least not unless it takes into consideration that workers add jobs to queue's too.

**Comment by bakura10** [comment]
I suspect that in Doctrine, evne wrapping everything in one transaction instead of many small one would already be beneficial, actually.

I'm currently ultra busy with front-end job, but once I'm done I'll try to come up with the code (or feel free to implement this idea at least on SlmQueue, on SlmQueue we basically only need the Comitter interface and an abstract class).

**Comment by basz** [comment]
@bakura10 yes that's true indeed. Would require a table type that's capable of transactions which we provide by default. I see no complications for SlmQueueDoctrine

**Comment by juriansluiman** [comment]
Cool idea! Haven't thought about it this way, but with batch processing and transactional updates, you kind-of get to this topic too. Some comments:

@bakura10 
> Yeah but the fact that it decorates a queue make it less flexible. My interface idea you could even push to different queue (potentially using different adapters) in a homogeneous way.

I am not sure it is such a good idea to mix a "committer" over different queues. I am not really sure, but like common DBAL implementations, you have a transaction per underlying system, so should you really create an umbrella for all of this?

@basz 
> The __destruct method is not a good idea. At least not unless it takes into consideration that workers add jobs to queue's too.

Although I agree __destruct() should not be used for features like this, I was assuming @bakura10 was thinking about the producer side and not the consumer side. And if you are inserting new jobs from a running job, I wouldn't use this feature but push into a queue directly.

@ltouro
> Just an ideia. I don't know how safe it is to use deconstruct.

I would rather argue that you could throw an exception when there are left-over jobs in the committer stage. So you are not actually depending on deconstruction to commit the jobs, but rather inform the user that persistency hasn't been established yet.

**In general**

I think it would be a good idea to have such thing, but can't we do something with batch processing instead (which seems more easier to understand / implement)? SQS has a batch built into the protocol. And (sssht, it is still a secret) I am working on ActiveMQ where you can open a connection, send multiple jobs and close the connection afterwards too. So is a batch feature perhaps more usable from a user's perspective?

I am just guessing here, because I forsee scenario's where you have a code path where you forget to "commit"  your jobs, which will have a great impact. A batch is easier to implement. And are there so many cases for multiple job insertions and different code points this really is an issue?

Another thought: I directly came up with the term of Unit Of Work, although that pattern is quite more complicated than above example. Perhaps it can give you some more insights in a possible implementation @bakura10 .

**Comment by bakura10** [comment]
I agree, and batch processing works really well actually, but as I told, what if you trigger an event and that five completely unrelated listeners need to add a job?

How can you implement batch processing in this use case?

With the future feature of middleware in zf3 it will be quite easy to actually register a new middleware that run at the end and that is responsible for flushing everything.

Envoyé de mon iPhone

**Comment by juriansluiman** [comment]
> With the future feature of middleware in zf3 it will be quite easy to actually register a new middleware that run at the end and that is responsible for flushing everything.

Well, I haven't thought about the middleware case even yet, but now I see where you're heading. 

Reading more about the UoW pattern, I guess this should be the way to go. If you simply rename your WIP title from "Committer" to "UnitOfWork", we already have a great start. I guess we have to think about two things:

1. Do you want to track jobs for all available queues, or have a dedicated UoW for every queue? Side question: can we open one transaction for sending jobs to multiple queues (e.g. for ActiveMQ this is possible) or a single transaction per queue?
2. Do you want to track life cycle of the jobs in UoW? This means, can you retrieve set jobs which are not persisted, to change its data (e.g. add job A, add job B, modify state A to A*)?

**Comment by bakura10** [comment]
I've updated the title.

1. I think the unit of work should be agnostic of queue. You add a job to the unit of work, to a given queue. It is then the adapter that is responsible to push everything in the most efficient manner. For example SQS does not allow to batch push to multiple queues, so it will iterate them all.

2. Hhhmmm... I'm not sure. Will think about it.

**Comment by roelvanduijnhoven** [comment]
I'll close this one as it more than two years old. Feel free to open new issue if ideas still relevant and / or interested in fixing! :)
