### ISSUE TITLE
Troubles with MaxMemoryStrategy

### ISSUE THREAD

**Issue by malinink** [JouwWeb/SlmQueue#163]
Hello, I have met interesting bug.

I have zf2 application with Doctrine2 (ORM + ODM(mongodb)) with configured queue called 'fetch'

I use it's own config:

```
return [
    'slm_queue' => [
        'queues' => [],
        'worker_strategies' => [
            'default' => [
                'Common\Queue\Strategy\ClearEntityManagerStrategy',
                'Common\Queue\Strategy\ClearDocumentManagerStrategy',
            ],
            'queues' => [
                'default' => [
                    'SlmQueue\Strategy\MaxMemoryStrategy'   => ['max_memory' => 30 * 1024 * 1024],
                    'SlmQueue\Strategy\MaxRunsStrategy'     => ['max_runs' => 40],
                ],
                'fetch' => [
                    'SlmQueue\Strategy\ProcessQueueStrategy',
                    'SlmQueue\Strategy\MaxMemoryStrategy'   => ['max_memory' => 40 * 1024 * 1024],
                    'SlmQueue\Strategy\MaxRunsStrategy'     => ['max_runs' => 20],
                ],
               ],
            ],
        ],
        'queue_manager' => [
            'factories' => [
                'default'   => 'SlmQueueDoctrine\Factory\DoctrineQueueFactory',
                'fetch'     => 'SlmQueueDoctrine\Factory\DoctrineQueueFactory',
            ],
        ],
    ],
];
```

Queue works fine, but my server goes down cause of swap....

I found that the main reason is ram, that used by queue.
In htop there are all fetch processes:
![fetch](https://cloud.githubusercontent.com/assets/5726553/8431079/98a2d2b6-1f3f-11e5-80c0-dd48a2b1d0f2.png)
![fetch1](https://cloud.githubusercontent.com/assets/5726553/8431080/9cb441b4-1f3f-11e5-949a-b664463e3c36.png)

I'v made a hook into  MaxMemoryStrategy
`echo sprintf('%s memory usage', $this->humanFormat($usage));`

Provided content for that queue is

```
2015-06-30 15:16:18,236 DEBG 'fetch-queue_0' stdout output:
28.73MB memory usage
2015-06-30 15:16:18,296 DEBG 'fetch-queue_5' stdout output:
30.18MB memory usage
2015-06-30 15:16:18,445 DEBG 'fetch-queue_2' stdout output:
28.73MB memory usage
2015-06-30 15:16:18,575 DEBG 'fetch-queue_1' stdout output:
28.73MB memory usage
2015-06-30 15:16:18,624 DEBG 'fetch-queue_4' stdout output:
28.73MB memory usage
2015-06-30 15:16:18,738 DEBG 'fetch-queue_3' stdout output:
28.73MB memory usage
```

So, it uses much more memory that it suppose to.

Have anybody ideas why that is so?

**Comment by basz** [comment]
Not sure what is going on, but you might try to debug the measurements within your job at several places...

Suppose a job starts with a memory usage of ~15Mb on invocation of it's execute method. During its work it might consume lots of memory (eg. image processing) which isn't detectable by the MaxMemoryStrategy if the job cleans up after itself correctly. The MaxMemoryStrategy only detects memory usage between jobs.

Also remember that the threshold is *per* process.

**Comment by malinink** [comment]
Hi, I make research before that and I catch that, but even one process with that configure could be more than 100Mb, In my particular case one thread is 173Mb, others 75, 70, 65 and 60Mb respectively.

I can't catch why that thread take so much memory. May be you have any ideas what else could I do to resolve problem?

**Comment by malinink** [comment]
After more research I found way to get real system memory consumption 

```php
$pid = getmypid();
$usage = ((int)(`ps --pid $pid --no-headers -orss`))*1024;
```
But I don't really sure that it's a good idea to use that code in MaxMemoryStrategy by default,
I could do one more option to choose getUsage algorithm, what do you think?

**Comment by basz** [comment]
My opinion is that if you really need this functionality you could create a PR for it (and yes some sort of option to enable such a feature would be best), but I honestly don't expect much from it. But then again I don't (can't) accept PR's for this repo :-) (ping @juriansluiman)

Consider the following first.

As said earlier this strategy only measures between jobs. If a job consumes a lot of memory and then releases it when it is finished the strategy will not (should not) exit. But high memory consumption might still crash the worker/server.

I think of this strategy more as a memory leak prevention while developing and a safeguard in production. Consider that even with a perfect solution for this, you would end up with unprocessed jobs because there simply isn't enough memory.

I recommend you check your jobs code, possibly break them down into smaller units. Do memory checks within a job class and possible bailout if memory it getting tight. Run fewer memory consuming queues in concurrency or increase your swap size. Obviously getting more RAM is an easy way out.

best of luck

ps. on os x the command seems to be `ps -p xxx -orss` and there is no `--no-headers` options so any output will contain the header.

**Comment by malinink** [comment]
Thanks a lot, I catch that!

I will think about breaking down my code, of course it's memory leaks. I just thought that 'real' measure will be better, because it could restart process depending on real memory limits.
